<MyGridLayout>:
    GridLayout:
        cols:1
        # Set the size of the grid layout
        size: root.width, root.height

        GridLayout:
            cols:2

            Label:
                text: "Name"
            TextInput:
                multiline: False

            Label:
                text: "First Name"
            TextInput:
                multiline: False

        Button:
            text: "Click me!"