<MyLayout>:
    BoxLayout:

        orientation: "vertical"
        size: root.width, root.height

        Carousel:
            #direction: "top"
            #direction: "bottom"
            direction: "right"
            AsyncImage:
                source: "https://cdn.pixabay.com/photo/2021/07/16/09/54/travel-6470467_960_720.jpg"
            Image:
                source: "images/tutter.jpg"
            Image:
                source: "images/tutter2.jpg"
